### ISSUE TITLE
Notifications Not Being Received; Issues With Checklist Storage

### ISSUE THREAD

**Issue by TurboProgramming** [Nathan2019/Calculator#13]
Notifications Not Being Received; Issues With Checklist Storage

**Comment by Nathan2019** [comment]
This has been fixed about 1 day ago! Notifications have been re-implemented.

**Comment by Nathan2019** [comment]
Issue is persisting again!

**Comment by Nathan2019** [comment]
A fix has been added! Is being tested.

**Comment by Nathan2019** [comment]
This has been fixed!
