### ISSUE TITLE
Add Splash Screen (Unexpected Halt)

### ISSUE THREAD

**Issue by TurboProgramming** [Nathan2019/Calculator#14]
Add Splash Screen (Unexpected Halt)

**Comment by Nathan2019** [comment]
Splash Screen has experienced a bug... That must be fixed by developers! Will be added soon

**Comment by Nathan2019** [comment]
Bug has been fixed! Splashscreen was re-implemented

**Comment by Nathan2019** [comment]
Removed Splash Screen
