### ISSUE TITLE
Fingerprint App Lock

### ISSUE THREAD

**Issue by TurboProgramming** [Nathan2019/Calculator#6]
Add Fingerprint App Lock (Eligible Devices Only)

**Comment by Nathan2019** [comment]
This feature has been implemented and completed!

**Comment by Nathan2019** [comment]
Fingerprint App Lock Requirements:

1. Must Have 1+ Fingerprints Added
2. Must Have A Fingerprint Scanner/Reader

**Comment by Nathan2019** [comment]
Receiving error when compiling... Fingerprint signin will be halted to a stop in this update and the next!
